#/bin/bash


wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/01/Campfire.png/50px-Campfire.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/d/d6/Stone_Hatchet.png/50px-Stone_Hatchet.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/4f/Spear.png/50px-Spear.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/c/cc/Note.png/50px-Note.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/6/69/Cloth_Pants.png/50px-Cloth_Pants.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f0/Cloth_Shirt.png/50px-Cloth_Shirt.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/43/Thatch_Foundation.png/50px-Thatch_Foundation.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/e/e7/Thatch_doorframe.png/50px-Thatch_doorframe.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/2/2a/Waterskin_%28Image_2%29.png/50px-Waterskin_%28Image_2%29.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/9/9e/Cloth_Gloves.png/50px-Cloth_Gloves.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/3/36/Cloth_Boots.png/50px-Cloth_Boots.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/42/Cloth_Hat.png/50px-Cloth_Hat.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/2/22/Wooden_Sign.png/50px-Wooden_Sign.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/e/e8/Hide_Sleeping_Bag.png/50px-Hide_Sleeping_Bag.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/d/da/Thatch_Roof.png/50px-Thatch_Roof.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/b/bd/Thatch_Wall.png/50px-Thatch_Wall.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/04/Thatch_door.png/50px-Thatch_door.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/3/3f/Slingshot.png/50px-Slingshot.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/d/d0/Storage_Box.png/50px-Storage_Box.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/b/b1/Simple_Bed.png/50px-Simple_Bed.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/b/bb/Phiomia_Saddle.png/50px-Phiomia_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f0/Mortar_And_Pestle.png/50px-Mortar_And_Pestle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/5/56/Sparkpowder.png/50px-Sparkpowder.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/9/92/Blood_Extraction_Syringe.png/50px-Blood_Extraction_Syringe.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/e/e6/Narcotic.png/50px-Narcotic.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/c/c4/Paintbrush.png/50px-Paintbrush.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/7/76/Flag.png/50px-Flag.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/6/60/Standing_Torch.png/50px-Standing_Torch.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/fb/Wooden_Foundation.png/50px-Wooden_Foundation.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/08/Wooden_Wall.png/50px-Wooden_Wall.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f9/Cooking_Pot.png/50px-Cooking_Pot.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/03/Cementing_Paste.png/50px-Cementing_Paste.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/e/e2/Stimulant.png/50px-Stimulant.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/ae/Gunpowder.png/50px-Gunpowder.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/5/57/Flare_Gun.png/50px-Flare_Gun.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/9/92/Compass.png/50px-Compass.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/c/c1/Spyglass.png/50px-Spyglass.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/5/59/Small_Crop_Plot.png/50px-Small_Crop_Plot.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/b/b6/Parasaur_Saddle.png/50px-Parasaur_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/b/bb/Phiomia_Saddle.png/50px-Phiomia_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/6/68/Stone_Irrigation_Pipe_-_Intake.png/50px-Stone_Irrigation_Pipe_-_Intake.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/a3/Stone_Irrigation_Pipe_Straight.png/50px-Stone_Irrigation_Pipe_Straight.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/c/c9/Stone_Irrigation_Pipe_Tap.png/50px-Stone_Irrigation_Pipe_Tap.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/00/Wooden_Spike_Wall.png/50px-Wooden_Spike_Wall.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/c/cb/Wooden_Wall_Sign.png/50px-Wooden_Wall_Sign.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/c/cf/Wooden_Ceiling.png/50px-Wooden_Ceiling.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/8/8c/Wooden_Doorframe.png/50px-Wooden_Doorframe.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/2/2c/Wooden_Door.png/50px-Wooden_Door.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f3/Wooden_Fence_Foundation.png/50px-Wooden_Fence_Foundation.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/44/Hide_Pants.png/50px-Hide_Pants.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f3/Hide_Shirt.png/50px-Hide_Shirt.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/6/65/Bow.png/50px-Bow.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/2/28/Stone_Arrow.png/50px-Stone_Arrow.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/1/1d/Large_Storage_Box.png/50px-Large_Storage_Box.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/8/86/Parachute.png/50px-Parachute.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/4b/Raptor_Saddle.png/50px-Raptor_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/d/d2/Stone_Irrigation_Pipe_Intersection.png/50px-Stone_Irrigation_Pipe_Intersection.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/3/3d/Stone_Irrigation_Pipe_Inclined.png/50px-Stone_Irrigation_Pipe_Inclined.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/9/90/Stone_Irrigation_Pipe_Vertical.png/50px-Stone_Irrigation_Pipe_Vertical.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/e/e1/Compost_Bin.png/50px-Compost_Bin.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/c/c0/Stone_Fence_Foundation.png/50px-Stone_Fence_Foundation.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/1/1e/Stone_Wall.png/50px-Stone_Wall.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/2/2c/Water_Reservoir.png/50px-Water_Reservoir.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/01/Wooden_Billboard.png/50px-Wooden_Billboard.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f4/Wooden_Ramp.png/50px-Wooden_Ramp.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/a8/Dinosaur_Gateway.png/50px-Dinosaur_Gateway.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/b/b7/Dinosaur_Gate.png/50px-Dinosaur_Gate.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/3/39/Wooden_Pillar.png/50px-Wooden_Pillar.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/9/9a/Wooden_Hatchframe.png/50px-Wooden_Hatchframe.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/c/c7/Wooden_Ladder.png/50px-Wooden_Ladder.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/09/Hide_Gloves.png/50px-Hide_Gloves.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/5/56/Hide_Boots.png/50px-Hide_Boots.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/9/92/Hide_Hat.png/50px-Hide_Hat.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/b/be/Tranquilizer_Arrow.png/50px-Tranquilizer_Arrow.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/9/98/Refining_Forge.png/50px-Refining_Forge.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/d/de/Trike_Saddle.png/50px-Trike_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/09/Preserving_Bin.png/50px-Preserving_Bin.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/c/c3/Wooden_Catwalk.png/50px-Wooden_Catwalk.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f1/Wooden_Trapdoor.png/50px-Wooden_Trapdoor.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/0b/Wooden_Windowframe.png/50px-Wooden_Windowframe.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f6/Stone_Foundation.png/50px-Stone_Foundation.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/d/d0/Stone_Ceiling.png/50px-Stone_Ceiling.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/41/Stone_Doorframe.png/50px-Stone_Doorframe.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/47/Reinforced_Wooden_Door.png/50px-Reinforced_Wooden_Door.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/6/6b/Stone_Dinosaur_Gateway.png/50px-Stone_Dinosaur_Gateway.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/0d/Reinforced_Dinosaur_Gate.png/50px-Reinforced_Dinosaur_Gate.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f7/Bookshelf.png/50px-Bookshelf.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/b/b9/Smithy.png/50px-Smithy.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/3/3a/Metal_Spike_Wall.png/50px-Metal_Spike_Wall.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/9/9f/Metal_Pick.png/50px-Metal_Pick.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/a6/Metal_Hatchet.png/50px-Metal_Hatchet.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/3/31/Pike.png/50px-Pike.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/7/7a/Pulmonoscorpius_Saddle.png/50px-Pulmonoscorpius_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/ac/Carbonemys_Saddle.png/50px-Carbonemys_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/d/d0/Medium_Crop_Plot.png/50px-Medium_Crop_Plot.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/ad/Metal_Sign.png/50px-Metal_Sign.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/6/60/Stone_Pillar.png/50px-Stone_Pillar.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/ae/Stone_Hatchframe.png/50px-Stone_Hatchframe.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/2/2c/Stone_Windowframe.png/50px-Stone_Windowframe.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/c/ca/Wooden_Window.png/50px-Wooden_Window.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/fd/Chitin_Leggings.png/50px-Chitin_Leggings.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f1/Chitin_Chestpiece.png/50px-Chitin_Chestpiece.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/7/7b/Chitin_Helmet.png/50px-Chitin_Helmet.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/47/Water_Jar.png/50px-Water_Jar.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/d/d0/Simple_Pistol.png/50px-Simple_Pistol.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/8/88/Simple_Bullet.png/50px-Simple_Bullet.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/6/63/Scope_Weapons.png/50px-Scope_Weapons.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/4c/Stego_Saddle.png/50px-Stego_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/fb/Grenade.png/50px-Grenade.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/7/73/Metal_Wall_Sign.png/50px-Metal_Wall_Sign.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/45/Metal_Foundation.png/50px-Metal_Foundation.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/a9/Metal_Wall.png/50px-Metal_Wall.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/d/db/Metal_Doorframe.png/50px-Metal_Doorframe.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/b/b9/Chitin_Gauntlets.png/50px-Chitin_Gauntlets.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/0d/Chitin_Boots.png/50px-Chitin_Boots.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/a2/Longneck_Rifle.png/50px-Longneck_Rifle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/a0/Simple_Rifle_Ammo.png/50px-Simple_Rifle_Ammo.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/ad/Large_Crop_Plot.png/50px-Large_Crop_Plot.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/9/92/Pteranodon_Saddle.png/50px-Pteranodon_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/a6/Sarco_Saddle.png/50px-Sarco_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/6/61/Shotgun.png/50px-Shotgun.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/1/18/Simple_Shotgun_Ammo.png/50px-Simple_Shotgun_Ammo.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/d/d8/Metal_Pillar.png/50px-Metal_Pillar.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/ac/Metal_Ceiling.png/50px-Metal_Ceiling.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/c/cd/Metal_Door.png/50px-Metal_Door.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/e/eb/Metal_Ramp.png/50px-Metal_Ramp.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/6/66/Fabricator.png/50px-Fabricator.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/9/94/Silencer_Weapons.png/50px-Silencer_Weapons.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/5/57/Ankylo_Saddle.png/50px-Ankylo_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/1/19/Mammoth_Saddle.png/50px-Mammoth_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/e/e4/Metal_Irrigation_Pipe_Intake.png/50px-Metal_Irrigation_Pipe_Intake.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/06/Metal_Irrigation_Pipe_Straight.png/50px-Metal_Irrigation_Pipe_Straight.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/e/e6/Metal_Hatchframe.png/50px-Metal_Hatchframe.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/e/e9/Metal_Trapdoor.png/50px-Metal_Trapdoor.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/3/3d/Metal_Fence_Foundation.png/50px-Metal_Fence_Foundation.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/47/Metal_Dinosaur_Gateway.png/50px-Metal_Dinosaur_Gateway.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/2/26/Metal_Dinosaur_Gate.png/50px-Metal_Dinosaur_Gate.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/8/81/Polymer.png/50px-Polymer.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/d/dd/Electronics.png/50px-Electronics.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/07/Flak_Leggings.png/50px-Flak_Leggings.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/6/62/Flak_Chestpeice.png/50px-Flak_Chestpeice.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/1/15/Improvised_Explosive_Device.png/50px-Improvised_Explosive_Device.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f1/Metal_Irrigation_Pipe_Intersection.png/50px-Metal_Irrigation_Pipe_Intersection.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/e/eb/Metal_Irrigation_Pipe_Inclined.png/50px-Metal_Irrigation_Pipe_Inclined.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/8/81/Metal_Irrigation_Pipe_Vertical.png/50px-Metal_Irrigation_Pipe_Vertical.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f4/Metal_Irrigation_Pipe_Tap.png/50px-Metal_Irrigation_Pipe_Tap.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/c/cc/Metal_Water_Reservoir.png/50px-Metal_Water_Reservoir.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/8/80/Megalodon_Saddle.png/50px-Megalodon_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/3/33/Sabertooth_Saddle.png/50px-Sabertooth_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/6/68/Metal_Windowframe.png/50px-Metal_Windowframe.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/5/5e/Metal_Ladder.png/50px-Metal_Ladder.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/4a/Flashlight_Weapons.png/50px-Flashlight_Weapons.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/7/72/GPS.png/50px-GPS.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/7/77/Flak_Boots.png/50px-Flak_Boots.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f2/Flak_Gauntlets.png/50px-Flak_Gauntlets.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/e/ec/Flak_Helmet.png/50px-Flak_Helmet.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/2/25/Metal_Billboard.png/50px-Metal_Billboard.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/1/11/Metal_Window.png/50px-Metal_Window.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/08/Metal_Catwalk.png/50px-Metal_Catwalk.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/a9/Carno_Saddle.png/50px-Carno_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/9/92/Electrical_Generator.png/50px-Electrical_Generator.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/1/1d/Straight_Electrical_Cable.png/50px-Straight_Electrical_Cable.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f3/Electrical_Outlet.png/50px-Electrical_Outlet.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/2/2e/Fabricated_Pistol.png/50px-Fabricated_Pistol.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/3/3e/Advanced_Bullet.png/50px-Advanced_Bullet.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/9/9b/Remote_Keypad.png/50px-Remote_Keypad.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/b/b1/Lamppost.png/50px-Lamppost.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/c/c3/Inclined_Electrical_Cable.png/50px-Inclined_Electrical_Cable.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/d/d5/Vertical_Electrical_Cable.png/50px-Vertical_Electrical_Cable.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/d/d0/Electrical_Cable_Intersection.png/50px-Electrical_Cable_Intersection.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/04/Argentavis_Saddle.png/50px-Argentavis_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/a2/Bronto_Saddle.png/50px-Bronto_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/d/d8/Refrigerator.png/50px-Refrigerator.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/2/25/Air_Conditioner.png/50px-Air_Conditioner.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/8/85/C4_Remote_Detonator.png/50px-C4_Remote_Detonator.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/46/C4_Charge.png/50px-C4_Charge.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/e/e0/Assault_Rifle.png/50px-Assault_Rifle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/6/64/Advanced_Rifle_Bullet.png/50px-Advanced_Rifle_Bullet.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/b/b3/Laser_Attachment.png/50px-Laser_Attachment.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/45/Holo-Scope.png/50px-Holo-Scope.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/4/49/Behemoth_Gateway.png/50px-Behemoth_Gateway.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/6/62/Behemoth_Gate.png/50px-Behemoth_Gate.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/a/af/Tyrannosaurus_saddle.png/50px-Tyrannosaurus_saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/9/97/Spino_Saddle.png/50px-Spino_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/8/8e/Plesiosaur_Saddle.png/50px-Plesiosaur_Saddle.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/0/05/Rocket_Launcher.png/50px-Rocket_Launcher.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/9/9e/Rocket_Propelled_Grenade.png/50px-Rocket_Propelled_Grenade.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/f/f9/Auto_Turret.png/50px-Auto_Turret.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/2/29/Heavy_Miners_Helmet.png/50px-Heavy_Miners_Helmet.png
wget http://hydra-media.cursecdn.com/ark.gamepedia.com/thumb/c/c9/Vault.png/50px-Vault.png

